import { Inter,Lexend_Deca,Bungee } from "next/font/google";

import "./globals.css";
const bungee = Bungee({ weight: '400', subsets: ['latin'] });
const inter = Inter({ subsets: ["latin"] });

const lexendDeca = Lexend_Deca({
  subsets: ['latin'],
});

export const metadata = {
  title: "FarmHash",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${inter.className} !top-0`}>{children}</body>
    </html>
  );
}
